export const EMERGENCY_DATA_ARR = [
    {
        name: "Sound the Alarm",
        content: "Acknowledge and raise awareness of the climate and ecological crisis - including its roots in systems of oppression - in our organisations and our practice."
    },
    {
        name: "Start the Journey",
        content: "Invest in educating ourselves and our teams on methods of sustainable and regenerative design, and show leadership by making measurable change to our practice. The Design Declares Toolkit is a great place to start."
    },
    {
        name: "Bring Clients with Us",
        content: "Meaningfully consider environmental and social impacts as part of every pitch, proposal and production process. Not every design output will be carbon neutral or fully climate friendly, but every project is an opportunity to make real progress."
    },
    {
        name: "Measure What We Make",
        content: "Measure the environmental and social impact of our businesses and design projects, and hold ourselves to account for what we find out."
    },
    {
        name: "Redefine ‘Good’",
        content: "Encourage, recognise and reward sustainable and regenerative design excellence in our industry through media and awards."
    },
    {
        name: "Educate, Accelerate",
        content: "Build and foster intra- and cross-discipline knowledge networks to share tools, resources and best practice to accelerate progress in our industry."
    },
    {
        name: "Design for Justice",
        content: "Create with and for the people who are disproportionately affected both by climate change and by the transition to a lower-carbon world."
    },
    {
        name: "Amplify Voices for Change",
        content: "Enable systemic change by working alongside policymakers, campaigners, ecologists, scientists, activists and others to strengthen local and national movements for change."
    }
];

export const SIGNATURES_ARR = [
    "21–87",
    "216 Signs",
    "31% Wool",
    "400",
    "A–Side.",
    "Aalia Ahamed",
    "Abbie Williams",
    "ACRE – A Creative Endeavour Ltd",
    "Active Matter",
    "ACX",
    "Adele Kelly",
    "AdesignStorie",
    "Advocate Design Agency",
    "Aetha Design",
    "Aileron Design Ltd",
    "Alan Pitchforth",
    "Alex Kimber Design",
    "Alexander Miller",
    "Alexandra Lunn Studio",
    "Alexandra Lunn Studio",
    "Alexie Sommer",
    "Alexis Bardini",
    "Ali Adair",
    "Andrew Carr",
    "ANdy Parker",
    "Andy Thornton",
    "Anja Klüver",
    "Annabelle Vuille",
    "Apfel",
    "Applied Works",
    "Archetype Accessories",
    "Arif Yusop",
    "Arrival",
    "Avery & Brown",
    "BA (Hons) Design for Sustainable Futures at Arts University Bournemouth",
    "BA Graphic Design at Kingston School of Art",
    "Badfish Labs",
    "Baines Design LTD",
    "Barbara Chandler",
    "Barbara Chandler",
    "Barry Bloye",
    "Batch.Works",
    "Baxter & Bailey",
    "Be The Future",
    "Beco",
    "Beehive Green",
    "Ben Clarke",
    "Ben Jessop",
    "Bencium Limited",
    "Benedict Povey",
    "Beta Design Office",
    "BIB Design",
    "big fish",
    "Big Motive",
    "Bill Searle",
    "Biomimicry Innovation Lab",
    "Bliss",
    "Blunt Crayon",
    "Bold Studio",
    "Boyle & Perks",
    "Brand Narrative at Pentagram",
    "Bravand",
    "Breezign",
    "Bright Signals Design at Bright Signals Ltd.",
    "Broadley Creative Ltd",
    "Bronwen Rees",
    "Buff Motion",
    "Butterfly",
    "BuyDesign",
    "Carter Studio",
    "Célibataire",
    "Charli Blighton",
    "Charli Peake",
    "Charlotte Eagle",
    "Charlotte Evans",
    "Cherry Anderson Freelance Design",
    "Chloe Poulter",
    "Claire O’Neill",
    "Claire Potter Design",
    "Clara Greo",
    "Clare Lewis",
    "Claudiu",
    "Clever Ghost",
    "Climate Labs",
    "Clive Russell",
    "COHDA Design",
    "Companion Studio",
    "Conscious Hospitality Ltd",
    "Conscious Sourcing",
    "Contour",
    "Creative at Delarki",
    "Creative Concern",
    "creative conscience",
    "Creative Joy",
    "Creative Joy",
    "Creative Wilderness LTD",
    "Curious Agency",
    "Curious Agency",
    "Curious Brand",
    "CyDen Ltd",
    "D Squared Product Development Ltd",
    "Daedalus",
    "Daryl Wilkinson",
    "Dave Cartledge",
    "Dave Cuvelot",
    "David Fairbrother",
    "David Sudlow Designers",
    "DEFY Brands",
    "Design Activists for Regenerative Futures",
    "Design Burger",
    "Design by Country Ltd",
    "Design by Mondial",
    "Design Council",
    "Design For Good Club",
    "Design for Joy",
    "Design Nature CIC",
    "Design Science",
    "Design Truth",
    "DesignWright",
    "DH Design Studios Ltd",
    "Dids Macdonald",
    "Dionne Griffith",
    "Diploma in Professional Studies at London College of Communication",
    "DISOMT",
    "Dominik Bini",
    "Dr Emma Powell",
    "Dr Karl Jeffries",
    "Drew Kendrick",
    "Driftime® Media",
    "Dylan Wiener",
    "ecologicstudio",
    "Edmuuund",
    "Electro Strategy",
    "Element Studio",
    "Eleven",
    "elise",
    "Ella Porter",
    "Elle Nelson Design",
    "Ellie Burroughs",
    "Emily Gorham",
    "EMMA BRITTAIN",
    "Emma Summerscales",
    "emmabakerstudio",
    "Eniola Ogunsola",
    "Ensemble",
    "Enviral",
    "Etch",
    "Ettive Design",
    "Europa",
    "Eva Koehle",
    "Everything",
    "Everywhere Design",
    "Exeter Waste",
    "F VENZANO",
    "Fairground Studio",
    "Farrah & Pearce Ltd",
    "FearNaught",
    "Fernanda Rizzo",
    "Ferrgood Studio",
    "Few and Far",
    "Fighting Talk Communications",
    "Fiona Watkins Design Limited",
    "Fixperts at Forth",
    "Foundation",
    "Founded Design Ltd",
    "Fourfeet Design",
    "Francesca Cook Design Ltd",
    "Francis Rowland",
    "Frankie Thelwell",
    "FranklinTill",
    "Future Island-Island at Ulster University-led consortium",
    "Future Selves",
    "Futurice Ltd",
    "Fynn",
    "G R Moore Limited",
    "G3 Creative",
    "Gareth Neal Ltd",
    "Gareth Wild",
    "Garlic Agency",
    "Genevieve Bennett Ltd",
    "Genuinely Conscious",
    "George Charnley",
    "George Rowland",
    "GET LOST",
    "Gianfranco Fagotto",
    "Gitta Gschwendtner Ltd",
    "Giulia Villa",
    "Glen Cutwerk",
    "Glimpse",
    "Good Design Works",
    "Good Stuff Creative",
    "Good Will Studios",
    "Goodtale",
    "Goodwin Hartshorn",
    "Graduate Studies at College for Creative Studies",
    "Graft Creative",
    "Green Mat Workshop",
    "Green Orbit Digital",
    "Green Rooms landscapes & gardens",
    "GreenHeights",
    "H&A",
    "Hamish Duncan",
    "Hamish Makgill",
    "Han Li",
    "Hannah Pinnock",
    "Harriet Beesley",
    "Harrison Brands Ltd",
    "Haughton Design",
    "Helen Simmons",
    "Hey Low",
    "Hippo Digital",
    "Hive IT",
    "Hiyield",
    "Holmes Studio",
    "honours",
    "HOUSE OF HACKNEY",
    "Hundred Studio",
    "ICE",
    "ilka design limited",
    "Imagination Factory",
    "Inspirwood",
    "INTRA DRIVE LTD",
    "Irina Teti",
    "Isabella",
    "Jackie Malcolm",
    "Jake Owen",
    "James Kindred",
    "James Tooze",
    "Jamie Pinkham",
    "jan lewis creative",
    "Jane Penty",
    "Jason Bruges Studio",
    "Jason Mesut",
    "Jemima Duncalf",
    "Jess Baxter",
    "Jess Francis",
    "JK Creative Company",
    "Jo Mansfield",
    "Joanna boehnert",
    "John Gilbert",
    "Joseph Folkes",
    "Josh Elgood",
    "Joshua Tunstill",
    "Jude Pullen",
    "Juice by Design",
    "Justine Wyness",
    "Kaelum van der Berg",
    "Kai Davis",
    "Kaleido Grafik",
    "Kaleido Grafik",
    "Kanika Kalra",
    "Karishma Kusurkar",
    "Kathryn Summers",
    "Kavya Narayanan",
    "Kenny Heard",
    "Kenwood Design Office (KDO) at Kenwood Limited",
    "Kim Trow",
    "Kinneir Dufort",
    "Kirsten Gord",
    "KLUVERWORKS",
    "Kyle Soo",
    "Kyle Stuart Florent Taylor",
    "Laura Santamaria",
    "Laure Rees-Smith",
    "Lawrence Zeegen",
    "Layerd.Studio",
    "Leap Design",
    "Lewis Plummer",
    "Liam O'Brien",
    "Lil Creative Studio",
    "Limber Brands",
    "Liquid Studio Ltd",
    "Lobo Creative",
    "LowCarbon",
    "Lucy Carruthers",
    "Lucy Watkins",
    "Luigi Gisolfi",
    "Lyon & Lyon",
    "MA Sustainable Design at University of Brighton",
    "Made for the World",
    "madeby.studio",
    "Magnus Long Studio",
    "Mainlyphotography Studio",
    "Mani I",
    "Mantra",
    "Mar Mar Co. Studio",
    "March Studio Ltd",
    "Maria Elina",
    "Marion Ratie",
    "Mark Hicks",
    "Marta De Prisco",
    "MARTA ROSSATO INTERIORS",
    "Martin Hopkins",
    "Martin Price",
    "Martin Wright",
    "Mat Denney",
    "Materialise Interiors",
    "Materials Council",
    "MaterialsInformation Ltd",
    "Matt Hollands",
    "Matteo Menapace",
    "Matter + Perspective",
    "Matthew Kilcullen",
    "Max Fraser",
    "Maya Designer",
    "Mia Allers",
    "Micha Nicheva",
    "Michael James",
    "Michael Love Design",
    "Michael Norrington",
    "Michael Rawling",
    "Midnight",
    "Minna Takala",
    "Mireia Allende",
    "Mitre and Mondays",
    "Mocean",
    "ModularPlastik",
    "Monica Oliveira",
    "MONOMOTIF",
    "Morrama",
    "Muddy Machines",
    "Muta Futures Studio",
    "Nagonic Design Ltd",
    "Naked Ideas",
    "Nat Hunter",
    "Natalia Benusiglio Stern",
    "Natalie Perkins",
    "Nefeli Pavlou Musio",
    "Neol.co",
    "Never Not Ready",
    "Nicola Holden Designs",
    "Nils Aksnes",
    "noel douglas",
    "Norah Joshi (Lewis)",
    "Noughts & Ones",
    "NU Creative Ltd",
    "NU Design Spaces",
    "Nurture",
    "Objective Studio",
    "observerly",
    "Octo Design Ltd",
    "OGRE Studio",
    "Ohana Studio Ltd",
    "Ok deploy",
    "Ole Makkesen Designlab",
    "Olive Kennington",
    "Oliver Lloyd",
    "Olivia Harris",
    "OneKind Creative",
    "Optimist Works",
    "Oracle Design",
    "Orangery",
    "ORCA",
    "Osch",
    "Other Today",
    "OURI Labs",
    "OXygen",
    "Papaya–Studio",
    "Papillon Bleu",
    "Paul Bailey",
    "Paul Gibson Design",
    "Pearson Lloyd",
    "People Planet Product",
    "Phase Two",
    "Pixel Fridge LTD",
    "Pollenize CIC",
    "Polytechnic",
    "Poonum Chauhan",
    "Pretty Clever",
    "Product Design at University of Brighton",
    "Product Design at University of Sussex",
    "Product for Net Zero",
    "Purple Banana",
    "QED web design",
    "Rahul Anand",
    "Realise",
    "Rebekah Di Palma",
    "ReShaped Landscape",
    "Rhapsody Media",
    "Rhombus Studio",
    "Ria Hawthorn",
    "Richa Gandhi",
    "Robin Wong",
    "Roddy Clarke",
    "Rory Cowan",
    "Roundwave",
    "Ruddocks",
    "Ruth Wassermann Ltd",
    "Sabotage",
    "Sam Judge",
    "Samuel Marchant",
    "Sandrine Herbert-Razafinjato",
    "sassd",
    "School of Good Services",
    "Selesti",
    "Selina Rose",
    "Set Studio",
    "Seth Campbell",
    "Sheffield Creative Industries Institute at Sheffield Hallam University",
    "Simone Cucchi",
    "Snook",
    "Social Change",
    "Sophie Mockridge",
    "Sophie Reynolds",
    "Sophie Thomas",
    "Spark & Bell",
    "Special Projects",
    "Spotless",
    "Sruti Gidugu",
    "Standfirst",
    "Stefan Bassing",
    "Still&Nimble",
    "Storo",
    "Straight Forward Design",
    "Stuart Gough",
    "Studio Breuil",
    "Studio Casey Joy",
    "Studio Elk",
    "Studio Elma",
    "Studio Every",
    "Studio Gallant",
    "Studio Joana",
    "Studio KICO",
    "Studio Mothership",
    "Studio Olivers",
    "Studio Ology",
    "Studio Output",
    "Studio Overberg",
    "Studio Simple",
    "Studio Technical Nature",
    "Studio Tom Metcalfe",
    "Studio Wood",
    "Submarine",
    "Substance",
    "Superfried",
    "Susanna Edwards",
    "Susannah Kabuiku",
    "Sustainable Ventures Design",
    "T&B Design",
    "Tacit-Tacit",
    "Takram",
    "TAMART",
    "Tempest",
    "TEN by Anatomy HCD Limited",
    "Teresa Ferreira Studio",
    "Terrarium",
    "The Art and Design Consultancy",
    "The Blooming Platypus",
    "The Creative Bloc",
    "The Digital Creative London Ltd.",
    "The Discourse",
    "THE FOURTH SOLUTION",
    "The Landscape",
    "The Looking Glass",
    "The Manufacturing Technology Centre",
    "Theo Dormer",
    "Think/Do",
    "Thinkpublic",
    "Thom Baker Consultancy",
    "Thomas Baraldi Cassaro",
    "Thomas Wylam",
    "thomas.matthews",
    "Thoughtcraft",
    "Tijana Tasich",
    "Tim Frenneaux & Co",
    "Tina Bernstein",
    "TLC",
    "Tokyo Calm",
    "Tokyo Calm",
    "Tom Greenwood",
    "Tomas Gecim",
    "Tommy Papaioannou",
    "Tria Design",
    "Tristan Palmer Studio",
    "Two",
    "Two Degrees Studio",
    "Tŷ Syml",
    "Unboxed",
    "Unfound Studio",
    "United by Design",
    "UnlikelyGenius",
    "URGE Collective",
    "Vashti Waite",
    "Vestre Ltd",
    "Vicky Lofthouse",
    "Virgile Janssen",
    "Visual Print and Design",
    "VIVID NINE",
    "Vovi",
    "Vox Aeris",
    "Vu Online",
    "We Are Service Works Ltd",
    "We Are Systematic",
    "We Made This Ltd",
    "We Mean This",
    "WEAMO",
    "West9 Design",
    "White Weft Limited",
    "Wholegrain Digital",
    "WizzDev",
    "Working with Joe Ltd",
    "Works in Public Ltd",
    "www.archety",
    "xforwhy",
    "XTATX Studio",
    "Yarn Creative",
    "yesim tuzun",
    "Yoke design",
    "Zebra Growth Limited",
    "Zoe Bather"
];

export const SUPPORTERS_ARR = [
    { country: "Argentina", participants: ["Celina Hilbert"] },
    { country: "Australia", participants: ["Alena Smith Interior Design", "Andrew Sloan", "Andrew Vaughan", "Andy Marks", "Arielle Breit", "Art Disrupt", "Austin Smidt", "AUTHENTIC DESIGN ALLIANCE (ADA)", "Ben Rennie", "BETTER FUTURE", "Bohdan Dorniak & Co Pty Ltd - PROSPECT, SA", "Brand & Communications at Edge Impact", "Breathe Architecture", "BWD Strategic", "Cameron Tonkinwise", "Carbon Creative", "Carolyn King", "Celine Waters", "Charlotte Adams", "Design by Nature", "Design Consigned", "Diadem", "Dr Michelle Douglas FRSA", "eco creative agency", "Ethos Digital Agency", "Finbar", "Founded by Design Pty Ltd", "Frost*", "Gabriella Wilson", "Genius Agency", "Geoff Isaac", "Glen Barry", "Gloria Quiroga", "Good 4 Business", "Good Design Australia", "Goodness", "Goodsports", "Hammond Studio", "Harry Steer", "Heidi Romano", "Holonic", "Hortenzia", "James Hodgson Design", "Jas Soh", "Jeremy Yuille", "Jo Li Tay", "John Young", "Josh Riesel", "Karina Clarke", "Katapult Design", "Kirby C", "Koskela", "Leigh Phillips-Brown", "Leigh-Anne Hepburn", "Leyla Acaroglu", "Liane Rossler", "LPB Designs and Interiors", "Madeline Johnston", "Make Tomorrow™", "Marnie Hawson", "Martin Tomitsch", "MEK Studio", "Mirella Arapian", "Moffitt.Moffitt.", "Motherbird", "Nacara Studio", "Nila Rezaei", "Particle Design Studio", "Philip Ely PhD", "philo & co", "Planitree", "Reny Studio", "Reny®", "Ricardo Sosa", "RK Collective", "RMIT University", "Samuel Yu", "Seek & Design", "Snug House", "Society for Responsible Design Inc.", "Sponge", "Stephanie Mulder", "Steve Baty", "STUDIO PERISCOPE", "Studio Regina", "studiospillane", "Tanisha Maria Naik", "The Design Thinkers", "UNEND", "United Studio", "vert design", "Wendy Fountain", "X+O", "Ys", "Zero Co pty Ltd"] },
    { country: "Austria", participants: ["GP designpartners"] },
    { country: "Belgium", participants: ["Bureaubakker", "DOGS OF DESIGN", "Goodwill", "Little Miss Robot", "Madoc bv"] },
    { country: "Brazil", participants: ["Natália Santos"] },
    { country: "Canada", participants: ["Brenda Reid", "Cooper Reid", "Vesna Savoie"] },
    { country: "Colombia", participants: ["Ana María Carrizosa", "Johanna Rojas", "Juanita Garcia", "Laura Restrepo", "Lina María Echeverri"] },
    { country: "Czech Republic", participants: ["Jan Petrik"] },
    { country: "Denmark", participants: ["Fair Designs", "Mette Jacobsen"] },
    { country: "Finland", participants: ["Miia Pölkki", "Sirpa Andersson"] },
    { country: "France", participants: ["Charlotte Arnal", "Émilie Cazin", "Paul Raux", "Sophie Flament"] },
    { country: "Germany", participants: ["Design for Sustainability (D4S)", "Nadine Richter"] },
    { country: "Greece", participants: ["Georgios Mavridis"] },
    { country: "India", participants: ["Kalpana Pot", "Parul Bhargava", "Ruchi Sharma"] },
    { country: "Ireland", participants: ["Martha Ryan"] },
    { country: "Italy", participants: ["Elisa Astorri", "Francesca Bergamaschi", "Leonardo Turelli", "Sara Dolfi Agostini"] },
    { country: "Japan", participants: ["Takako Konishi"] },
    { country: "Netherlands", participants: ["Geanne van Arkel", "Lisette Kreischer", "Marcel Kampman", "Reframing Studio", "Sandra Ballij", "Studio Dubbelepunt"] },
    { country: "New Zealand", participants: ["Andrew Sloan", "ArchiDesign Ltd", "Chloe Geoghegan", "Davor Popadich", "Design Assembly", "Eve Roach", "Jemma Blom", "John McArthur", "Kate McGuinness", "Madeleine Slade", "Mairéad Harkin", "Material Creative", "Nick Sterenberg", "Rebecca Waller", "Sarah Ritchie", "Simon Devitt", "Sophie McMillan", "Stephanie Liddicoat", "Studio Aeon", "Waka Kuaka Ltd"] },
    { country: "Nigeria", participants: ["Chidiebere Maduka"] },
    { country: "Norway", participants: ["Alexander von Krogh", "Joakim Formo"] },
    { country: "Portugal", participants: ["João Brandão"] },
    { country: "Singapore", participants: ["Adeline Seah", "Hunn Wai", "Kristine Tan", "Loong Wong"] },
    { country: "Slovenia", participants: ["Veronika Markovič"] },
    { country: "South Africa", participants: ["AB Design", "Heather Moore", "Rehab"] },
    { country: "Spain", participants: ["Olga Pérez", "Studio La Habitacion"] },
    { country: "Sweden", participants: ["Ewa Kumlin", "Maria Håkansson", "Michael Braungart", "Thomas Nyström"] },
    { country: "Switzerland", participants: ["Karin Frei", "Sophie Tournier"] },
    { country: "United Kingdom", participants: ["Alex Hobbs", "Amy Redfern", "Amy Rees", "Antonia Bonello", "Benedict Douglas", "Charlotte Beale", "Charlotte Dewar", "Christopher Wragg", "Daisy Greenaway", "Danny Miller", "Deyan Sudjic", "Emma Carter", "Emma Preston", "Esther Christian", "Felicity Collins", "Fiona Ellis", "George Martindale", "Gregory Goodall", "Harry Mitchell", "Helen Robinson", "Jack Renwick Studio", "Jake Lewis", "James May", "James Parkin", "Jenny Theolin", "Jessica Leitch", "Jonny Adams", "Joseph Lawrence", "Katie Treggiden", "Kimberley Chan", "Laura Gordon", "Laura Knight", "Laura Knights", "Lucy Black", "Marc Atkinson", "Mark Smith", "Marta Alonso", "Molly Penn", "Nathan Outlaw", "Nick Tyler", "Nicole Yershon", "Nina Brunner", "Penny Mordaunt", "Peter Buchanan", "Rachael Owen", "Rebecca Park", "Rebecca Wright", "Richard Black", "Richard Bullock", "Ruth Watson", "Sarah Hyndman", "Scott King", "Scott Smith", "Sebastian Conran", "Selina Donald", "Sophie Thomas", "Steve Edge", "Steve Price", "Sue Siddall", "Suzi Winstanley", "Thomas Heatherwick", "Toby Hadden", "Tom Dixon", "Tony Chambers", "Tracey Waller", "Tristram Hunt", "Yinka Ilori"] },
    { country: "United States", participants: ["Alex Buck", "Amy Golden", "Annie Lindgren", "Ashlee Piper", "Blake Johnson", "Brian Dougherty", "Bruce Mau", "Catherine Hughes", "David Bowers", "Elizabeth Knight", "Emily Pilloton", "Erin Huizenga", "Gabriella Gomez-Mont", "Holly Kretschmar", "Janet McKay", "Jeffrey York", "Jessica Brown", "Jessica Green", "John Bielenberg", "John Cary", "Joseph Hall", "Kate Stohr", "Katie Beverley", "Kelly Stevens", "Kristen Brown", "Laura Weiss", "Lisa Kay Solomon", "Marina McCoy", "Melanie Miller", "Michael Grant", "Mike Walker", "Mina Guli", "Natalie Nixon", "Neri Oxman", "Nicole Middleton Holloway", "Patrick Keenan", "Paula Scher", "Peter Buchanan", "Rachel Gutter", "Rachael Owen", "Richard Bullock", "Richard Poulin", "Rick Valicenti", "Samantha Fisher", "Sarah Brooks", "Scott Boylston", "Scott Smith", "Steve Edge", "Thomas Heatherwick", "Toby Hadden", "Tony Fry", "Veronica Fuerte"] }
];

export const ACCORDIAN_ARR = [
    {
        title: "The Role of Design",
        p: [
            "As designers working within an industry that relies on production and powers global consumption, we must acknowledge that we have had a role in bringing us to where we are now, and that we have an important role in what comes next.",
            "Because designers are makers. We make ideas real. We generate solutions. We build the world - dreaming up new futures and bringing them to life in ways that are beautiful, vital and impossible to resist. It’s not quite magic, but it feels like it."
        ],
    },
    {
        title: "Time for Change",
        p: [
            "Together with our clients, partners and colleagues across the supply chain, we are daring to reimagine the way we create every product, service, campaign and designed solution we put out into the world.",
            "It means introducing principles of sustainability, circularity and - ultimately - regenerative design into our practice to recapture and repurpose resources and materials.",
            "This means measuring and actively reducing the greenhouse gas emissions and resource use linked to our designs.",
            "And it means acting systemically - seeing the bigger picture and working with others to sharpen design’s incredible capacity to influence and accelerate climate repair and justice."
        ]
    },
    {
        title: "Act with Urgency",
        p: [
            "We know all we need to make this a reality. The information, the guidance, the inspiration and solutions are there. What design needs now is action - meaningful steps that can begin to connect what we know to what we do.",
            "This is the most important brief of our lives. Join us as we begin to design a climate-positive future.",
        ]
    }
]

export const COUNTRIES_ARR = ["Aruba",
    "Afghanistan",
    "Angola",
    "Anguilla",
    "Åland Islands",
    "Albania",
    "Andorra",
    "United Arab Emirates",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Burundi",
    "Belgium",
    "Benin",
    "Bonaire, Sint Eustatius and Saba",
    "Burkina Faso",
    "Bangladesh",
    "Bulgaria",
    "Bahrain",
    "Bahamas",
    "Bosnia and Herzegovina",
    "Saint Barthélemy",
    "Belarus",
    "Belize",
    "Bermuda",
    "Bolivia",
    "Brazil",
    "Barbados",
    "Brunei Darussalam",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Central African Republic",
    "Canada",
    "Cocos (Keeling) Islands",
    "Switzerland",
    "Chile",
    "China",
    "Côte d'Ivoire",
    "Cameroon",
    "Congo, The Democratic Republic of the",
    "Congo",
    "Cook Islands",
    "Colombia",
    "Comoros",
    "Cape Verde",
    "Costa Rica",
    "Cuba",
    "Curaçao",
    "Christmas Island",
    "Cayman Islands",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Dominica",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Egypt",
    "Eritrea",
    "Western Sahara",
    "Spain",
    "Estonia",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands (Malvinas)",
    "France",
    "Faroe Islands",
    "Micronesia, Federated States of",
    "Gabon",
    "United Kingdom",
    "Georgia",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Guinea",
    "Guadeloupe",
    "Gambia",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Greece",
    "Grenada",
    "Greenland",
    "Guatemala",
    "French Guiana",
    "Guam",
    "Guyana",
    "Hong Kong",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran, Islamic Republic of",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Saint Kitts and Nevis",
    "Korea, Republic of",
    "Kuwait",
    "Kazakhstan",
    "Lao People's Democratic Republic",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova, Republic of",
    "Montenegro",
    "Saint Martin (French part)",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestine, State of",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Réunion",
    "Romania",
    "Serbia",
    "Russian Federation",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten (Dutch part)",
    "Syrian Arab Republic",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor-Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan, Province of China",
    "Tanzania, United Republic of",
    "Ukraine",
    "Uganda",
    "United States Minor Outlying Islands",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Holy See (Vatican City State)",
    "Saint Vincent and the Grenadines",
    "Venezuela, Bolivarian Republic of",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Vietnam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe"]

export const DISCIPLINE_ARR = [
    "Communication Design", "Digital Design", "Service Design", "Product Design"
]


